SELECT
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
    JOIN BOOK B
    ON S.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR A
    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC