SELECT
    MONTH(C.START_DATE) MONTH, 
    C.CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS M ON C.CAR_ID = M.CAR_ID
WHERE DATE_FORMAT(C.START_DATE, "%Y-%m") BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(C.START_DATE), CAR_ID
ORDER BY MONTH(C.START_DATE), C.CAR_ID DESC
