SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE MONTH(START_DATE) = 10
) H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = "세단"
ORDER BY CAR_ID DESC